# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      #Install the latest pip
      sudo pip install -U pip
      # Then upgrade cffi
      sudo apt-get remove python-cffi
      sudo pip install — upgrade cffi
      sudo apt-get install git libpq-dev python-dev
      # Specify the version on install
      sudo pip install cryptography==1.7.2
      sudo pip install dbt
      dbt — help


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
