version: 2

sources:
  - name: staging
    schema: staging
    tables:
      - name: weather_forecasts
        description: This is weather forecast data available from Snowflake.
      - name: weather_locations
        description: This is weather forecast data available from Snowflake.

models:
  - name: stg_weather_forecasts_hashed
  - name: stg_weather_locations_hashed
  - name: weather_locations
  - name: weather_forecasts